name: Publish to Github Packages

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew clean
          ./gradlew build
      - name: Publish
        run: |
          chmod +x ./gradlew
          ./gradlew publish
